### ISSUE TITLE
Key Error on GSE Arm Button click

### ISSUE THREAD

**Issue by jtalier** [masa-umich/Ground-Support-Software#112]
To reproduce, add the GSE board and click the arm button (no server connection, no campaign). On click then the following error occurs

```
Traceback (most recent call last):
  File "/Users/jt/Desktop/Michigan/MASA/Avionics/Code/gui/Python/board.py", line 229, in <lambda>
    self.arm_button.clicked.connect(lambda: self.sendBoardState("Arm"))
  File "/Users/jt/Desktop/Michigan/MASA/Avionics/Code/gui/Python/board.py", line 478, in sendBoardState
    newState = self.stateNum["Armed"]
KeyError: 'Armed'
```

**Comment by jtalier** [comment]
changed due date to March 23, 2022

**Comment by jtalier** [comment]
@eislam Can you attach commit hash that this was fixed on?

**Comment by jtalier** [comment]
He didn't closing :(
