### ISSUE TITLE
GUI Randomly crashed

### ISSUE THREAD

**Issue by jtalier** [masa-umich/Ground-Support-Software#132]
In GitLab by @nkalan on Apr 4, 2022, 17:07

Was not actively operating GUI. Looking through server command line when GUI closed.

Server Log: 
<16:56:11> Raw server logging started under '2022-04-04-T165611'
<16:56:11> Server initialized. Waiting for clients to connect...
<16:56:11> Listening on 172.20.10.6:6969
<16:56:14> Connection established on COM13
<16:56:29> Got connection from 172.20.10.6
<16:56:30> New commander: 40a1f900f2fa4a8693baa682e58c1165 (172.20.10.6)
<16:56:53> Campaign '2022-04-04-T165653__Coldflow_Attempt_3_4-4-2022' started
<17:05:03> Clearing commander
<17:05:03> Closing connection to 172.20.10.6

Command Line: 
<16:57:09> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649105829, 'args': [4, 1]}
<16:57:11> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649105831, 'args': [4, 0]}
<16:57:19> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649105839, 'args': [6, 1]}
<16:57:21> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649105841, 'args': [6, 0]}
<16:57:28> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649105848, 'args': [7, 1]}
<16:57:30> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649105850, 'args': [7, 0]}
<16:58:10> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105890, 'args': [1, 1]}
<16:58:12> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105892, 'args': [1, 1]}
<16:58:14> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105894, 'args': [1, 1]}
<16:58:17> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105897, 'args': [1, 0]}
<16:58:32> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105912, 'args': [3, 1]}
<16:58:34> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105914, 'args': [3, 0]}
<16:58:50> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105930, 'args': [4, 1]}
<16:58:52> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105931, 'args': [4, 1]}
<16:58:54> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105934, 'args': [4, 0]}
<16:59:27> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105967, 'args': [5, 1]}
<16:59:29> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649105969, 'args': [5, 0]}
<16:59:34> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649105974, 'args': [10, 1]}
<16:59:36> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649105975, 'args': [10, 0]}
<17:00:42> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106042, 'args': [8, 1]}
<17:00:46> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106046, 'args': [8, 0]}
<17:01:00> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106060, 'args': [4, 1]}
<17:01:01> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106061, 'args': [4, 0]}
<17:01:12> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649106072, 'args': [4, 1]}
<17:01:13> {'function_name': 'set_vlv', 'target_board_addr': 0, 'timestamp': 1649106073, 'args': [4, 0]}
<17:01:30> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106089, 'args': [8, 1]}
<17:01:31> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106091, 'args': [8, 0]}
<17:01:38> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106098, 'args': [11, 1]}
<17:01:40> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106100, 'args': [11, 0]}
<17:01:53> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106113, 'args': [12, 1]}
<17:01:55> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106115, 'args': [12, 0]}
<17:02:04> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106124, 'args': [12, 1]}
<17:02:07> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106127, 'args': [12, 0]}
<17:02:19> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106139, 'args': [12, 1]}
<17:02:22> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106142, 'args': [12, 0]}
<17:04:23> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106262, 'args': [9, 1]}
<17:04:24> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106264, 'args': [9, 0]}
<17:04:33> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106273, 'args': [10, 1]}
<17:04:34> {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106274, 'args': [10, 0]}

Server Terminal: 
{'clientid': '40a1f900f2fa4a8693baa682e58c1165', 'command': 3, 'args': {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106139, 'args': [12, 1]}}
{'clientid': '40a1f900f2fa4a8693baa682e58c1165', 'command': 3, 'args': {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106142, 'args': [12, 0]}}
Parser failed with error  list index out of range
Parser failed with error  'NoneType' object has no attribute 'dict'
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
{'clientid': '40a1f900f2fa4a8693baa682e58c1165', 'command': 9, 'args': ['CET-00:06:27', 'NOTE', 'No actuator on fuel prevalve, so not using that']}
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
{'clientid': '40a1f900f2fa4a8693baa682e58c1165', 'command': 9, 'args': ['CET-00:06:58', 'NOTE', 'Make sure to check that pneumatics are oriented properly']}
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
{'clientid': '40a1f900f2fa4a8693baa682e58c1165', 'command': 3, 'args': {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106262, 'args': [9, 1]}}
{'clientid': '40a1f900f2fa4a8693baa682e58c1165', 'command': 3, 'args': {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106264, 'args': [9, 0]}}
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
{'clientid': '40a1f900f2fa4a8693baa682e58c1165', 'command': 3, 'args': {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106273, 'args': [10, 1]}}
{'clientid': '40a1f900f2fa4a8693baa682e58c1165', 'command': 3, 'args': {'function_name': 'set_vlv', 'target_board_addr': 2, 'timestamp': 1649106274, 'args': [10, 0]}}
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Traceback (most recent call last):
  File "C:\Users\MASA-Avionics\Desktop\gui\Python\server.py", line 321, in client_handler
    msg = clientsocket.recv(4096*8)  # if the data is ever bigger then this so help me
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Failed Packet from 172.20.10.6 (consecutive: 1)
Traceback (most recent call last):
  File "C:\Users\MASA-Avionics\Desktop\gui\Python\server.py", line 321, in client_handler
    msg = clientsocket.recv(4096*8)  # if the data is ever bigger then this so help me
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Failed Packet from 172.20.10.6 (consecutive: 2)
Traceback (most recent call last):
  File "C:\Users\MASA-Avionics\Desktop\gui\Python\server.py", line 321, in client_handler
    msg = clientsocket.recv(4096*8)  # if the data is ever bigger then this so help me
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Failed Packet from 172.20.10.6 (consecutive: 3)
Traceback (most recent call last):
  File "C:\Users\MASA-Avionics\Desktop\gui\Python\server.py", line 321, in client_handler
    msg = clientsocket.recv(4096*8)  # if the data is ever bigger then this so help me
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Failed Packet from 172.20.10.6 (consecutive: 4)
Traceback (most recent call last):
  File "C:\Users\MASA-Avionics\Desktop\gui\Python\server.py", line 321, in client_handler
    msg = clientsocket.recv(4096*8)  # if the data is ever bigger then this so help me
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range
Parser failed with error  list index out of range

**Comment by jtalier** [comment]
In GitLab by @nkalan on Apr 4, 2022, 17:07

changed due date to April 04, 2022

**Comment by jtalier** [comment]
Almost positive this is intended behavior, I have not seen this again but should occur when another connection is incoming that should not be. This is better handled in new server. Closing
